import { Conversa } from '../types';

export const conversasMock: Conversa[] = [
  {
    id: 'conv-001',
    clienteNome: 'Maria Fernanda',
    clienteFotoUrl: '',
    pedidoId: 'ped-001',
    numeroPedido: 1042,
    naoLidas: 2,
    ultimaMensagem: 'Obrigada! Estou aguardando 😊',
    dataUltimaMensagem: '2025-08-28T10:45:00',
    mensagens: [
      { id: 'msg-001', remetenteId: 'cli-001', remetenteNome: 'Maria Fernanda', ehLoja: false, conteudo: 'Oi! Quanto tempo mais ou menos pro pedido ficar pronto?', dataEnvio: '2025-08-28T10:20:00', lida: true },
      { id: 'msg-002', remetenteId: 'loja-001', remetenteNome: 'Burguer Mania', ehLoja: true, conteudo: 'Olá Maria! Seu pedido está sendo preparado, deve sair em uns 15 minutinhos 🍔', dataEnvio: '2025-08-28T10:22:00', lida: true },
      { id: 'msg-003', remetenteId: 'cli-001', remetenteNome: 'Maria Fernanda', ehLoja: false, conteudo: 'Perfeito, obrigada!', dataEnvio: '2025-08-28T10:23:00', lida: true },
      { id: 'msg-004', remetenteId: 'loja-001', remetenteNome: 'Burguer Mania', ehLoja: true, conteudo: 'Seu pedido já saiu para entrega! 🚗', dataEnvio: '2025-08-28T10:40:00', lida: true },
      { id: 'msg-005', remetenteId: 'cli-001', remetenteNome: 'Maria Fernanda', ehLoja: false, conteudo: 'Obrigada! Estou aguardando 😊', dataEnvio: '2025-08-28T10:45:00', lida: false },
    ],
  },
  {
    id: 'conv-002',
    clienteNome: 'João Pedro',
    clienteFotoUrl: '',
    pedidoId: 'ped-002',
    numeroPedido: 1043,
    naoLidas: 1,
    ultimaMensagem: 'Conseguem trocar o suco de laranja por limonada?',
    dataUltimaMensagem: '2025-08-28T10:35:00',
    mensagens: [
      { id: 'msg-006', remetenteId: 'cli-002', remetenteNome: 'João Pedro', ehLoja: false, conteudo: 'Boa tarde! Conseguem trocar o suco de laranja por limonada?', dataEnvio: '2025-08-28T10:35:00', lida: false },
    ],
  },
  {
    id: 'conv-003',
    clienteNome: 'Beatriz Lima',
    clienteFotoUrl: '',
    pedidoId: 'ped-003',
    numeroPedido: 1044,
    naoLidas: 0,
    ultimaMensagem: 'Combinado, teremos o troco!',
    dataUltimaMensagem: '2025-08-28T11:10:00',
    mensagens: [
      { id: 'msg-007', remetenteId: 'cli-003', remetenteNome: 'Beatriz Lima', ehLoja: false, conteudo: 'Oi! Vocês têm troco para R$200?', dataEnvio: '2025-08-28T11:05:00', lida: true },
      { id: 'msg-008', remetenteId: 'loja-001', remetenteNome: 'Burguer Mania', ehLoja: true, conteudo: 'Oi Beatriz! Temos sim, sem problema 😊', dataEnvio: '2025-08-28T11:07:00', lida: true },
      { id: 'msg-009', remetenteId: 'cli-003', remetenteNome: 'Beatriz Lima', ehLoja: false, conteudo: 'Ótimo, obrigada!', dataEnvio: '2025-08-28T11:08:00', lida: true },
      { id: 'msg-010', remetenteId: 'loja-001', remetenteNome: 'Burguer Mania', ehLoja: true, conteudo: 'Combinado, teremos o troco!', dataEnvio: '2025-08-28T11:10:00', lida: true },
    ],
  },
  {
    id: 'conv-004',
    clienteNome: 'Thiago Mendes',
    clienteFotoUrl: '',
    pedidoId: 'ped-006',
    numeroPedido: 1045,
    naoLidas: 3,
    ultimaMensagem: 'Entregador pode ligar quando chegar? Moro em condomínio.',
    dataUltimaMensagem: '2025-08-28T11:40:00',
    mensagens: [
      { id: 'msg-011', remetenteId: 'cli-004', remetenteNome: 'Thiago Mendes', ehLoja: false, conteudo: 'Olá! Meu pedido já saiu?', dataEnvio: '2025-08-28T11:32:00', lida: false },
      { id: 'msg-012', remetenteId: 'cli-004', remetenteNome: 'Thiago Mendes', ehLoja: false, conteudo: 'O brownie pode vir com bastante calda? 🍫', dataEnvio: '2025-08-28T11:35:00', lida: false },
      { id: 'msg-013', remetenteId: 'cli-004', remetenteNome: 'Thiago Mendes', ehLoja: false, conteudo: 'Entregador pode ligar quando chegar? Moro em condomínio.', dataEnvio: '2025-08-28T11:40:00', lida: false },
    ],
  },
  {
    id: 'conv-005',
    clienteNome: 'Camila Rodrigues',
    clienteFotoUrl: '',
    pedidoId: 'ped-005',
    numeroPedido: 1040,
    naoLidas: 0,
    ultimaMensagem: 'Pedido cancelado. Desculpe pelo transtorno!',
    dataUltimaMensagem: '2025-08-28T09:15:00',
    mensagens: [
      { id: 'msg-014', remetenteId: 'cli-005', remetenteNome: 'Camila Rodrigues', ehLoja: false, conteudo: 'Oi, faz muito tempo que pedi... ainda vai demorar?', dataEnvio: '2025-08-28T09:00:00', lida: true },
      { id: 'msg-015', remetenteId: 'loja-001', remetenteNome: 'Burguer Mania', ehLoja: true, conteudo: 'Oi Camila, peço desculpas pela demora! Estamos com o movimento alto hoje 😓', dataEnvio: '2025-08-28T09:05:00', lida: true },
      { id: 'msg-016', remetenteId: 'cli-005', remetenteNome: 'Camila Rodrigues', ehLoja: false, conteudo: 'Vou cancelar então, preciso almoçar logo...', dataEnvio: '2025-08-28T09:10:00', lida: true },
      { id: 'msg-017', remetenteId: 'loja-001', remetenteNome: 'Burguer Mania', ehLoja: true, conteudo: 'Pedido cancelado. Desculpe pelo transtorno!', dataEnvio: '2025-08-28T09:15:00', lida: true },
    ],
  },
];
