import { Pedido } from '../types';

export const pedidosMock: Pedido[] = [
  {
    id: 'ped-001',
    numeroPedido: 1042,
    clienteNome: 'Maria Fernanda',
    clienteTelefone: '11991234567',
    itens: [
      { produtoId: 'prod-001', nomeProduto: 'X-Burguer Clássico', quantidade: 2, precoUnitario: 28.9, adicionais: ['Bacon', 'Cheddar extra'] },
      { produtoId: 'prod-008', nomeProduto: 'Coca-Cola 350ml', quantidade: 2, precoUnitario: 7.0 },
    ],
    valorTotal: 71.8,
    status: 'preparando',
    formaPagamento: 'Cartão de crédito',
    enderecoEntrega: 'Rua das Flores, 123 - Centro',
    dataCriacao: '2025-08-28T10:15:00',
    observacoes: 'Sem cebola no lanche, por favor.',
  },
  {
    id: 'ped-002',
    numeroPedido: 1043,
    clienteNome: 'João Pedro',
    clienteTelefone: '11992345678',
    itens: [
      { produtoId: 'prod-004', nomeProduto: 'Pizza Margherita', quantidade: 1, precoUnitario: 49.9, adicionais: ['Grande (8 fatias)'] },
      { produtoId: 'prod-009', nomeProduto: 'Suco de Laranja Natural', quantidade: 2, precoUnitario: 12.0 },
    ],
    valorTotal: 73.9,
    status: 'pendente',
    formaPagamento: 'Pix',
    enderecoEntrega: 'Av. Paulista, 1000 - Bela Vista',
    dataCriacao: '2025-08-28T10:30:00',
  },
  {
    id: 'ped-003',
    numeroPedido: 1044,
    clienteNome: 'Beatriz Lima',
    clienteTelefone: '11993456789',
    itens: [
      { produtoId: 'prod-013', nomeProduto: 'Combo Família', quantidade: 1, precoUnitario: 119.9 },
    ],
    valorTotal: 119.9,
    status: 'aceito',
    formaPagamento: 'Dinheiro',
    enderecoEntrega: 'Rua Augusta, 500 - Consolação',
    dataCriacao: '2025-08-28T11:00:00',
    observacoes: 'Troco para R$200',
  },
  {
    id: 'ped-004',
    numeroPedido: 1041,
    clienteNome: 'Rafael Souza',
    clienteTelefone: '11994567890',
    itens: [
      { produtoId: 'prod-003', nomeProduto: 'Smash Burger Duplo', quantidade: 1, precoUnitario: 36.0 },
      { produtoId: 'prod-006', nomeProduto: 'Porção de Batata Frita', quantidade: 1, precoUnitario: 22.0 },
      { produtoId: 'prod-008', nomeProduto: 'Coca-Cola 350ml', quantidade: 1, precoUnitario: 7.0 },
    ],
    valorTotal: 65.0,
    status: 'entregue',
    formaPagamento: 'Cartão de débito',
    enderecoEntrega: 'Rua Oscar Freire, 200 - Jardins',
    dataCriacao: '2025-08-28T09:30:00',
  },
  {
    id: 'ped-005',
    numeroPedido: 1040,
    clienteNome: 'Camila Rodrigues',
    clienteTelefone: '11995678901',
    itens: [
      { produtoId: 'prod-014', nomeProduto: 'Salada Caesar', quantidade: 1, precoUnitario: 29.9 },
      { produtoId: 'prod-009', nomeProduto: 'Suco de Laranja Natural', quantidade: 1, precoUnitario: 12.0 },
    ],
    valorTotal: 41.9,
    status: 'cancelado',
    formaPagamento: 'Pix',
    enderecoEntrega: 'Alameda Santos, 800 - Cerqueira César',
    dataCriacao: '2025-08-28T08:45:00',
    observacoes: 'Cliente cancelou por demora.',
  },
  {
    id: 'ped-006',
    numeroPedido: 1045,
    clienteNome: 'Thiago Mendes',
    clienteTelefone: '11996789012',
    itens: [
      { produtoId: 'prod-011', nomeProduto: 'Brownie com Sorvete', quantidade: 2, precoUnitario: 19.9 },
      { produtoId: 'prod-012', nomeProduto: 'Petit Gateau', quantidade: 1, precoUnitario: 24.9 },
    ],
    valorTotal: 64.7,
    status: 'saiu_entrega',
    formaPagamento: 'Vale-refeição',
    enderecoEntrega: 'Rua Haddock Lobo, 350 - Cerqueira César',
    dataCriacao: '2025-08-28T11:30:00',
  },
];
