import { Produto } from '../types';

export const produtosMock: Produto[] = [
  {
    id: 'prod-001',
    nome: 'X-Burguer Clássico',
    descricao: 'Pão artesanal, hambúrguer 180g, queijo cheddar, alface, tomate e molho especial.',
    fotoUrl: 'https://placehold.co/400x300/FF6961/FFFFFF?text=X-Burguer',
    categoria: 'Hambúrgueres',
    preco: 28.9,
    ativo: true,
    adicionais: [
      {
        id: 'grp-001',
        nome: 'Ponto da carne',
        obrigatorio: true,
        minimo: 1,
        maximo: 1,
        itens: [
          { id: 'ad-001', nome: 'Mal passada', preco: 0 },
          { id: 'ad-002', nome: 'Ao ponto', preco: 0 },
          { id: 'ad-003', nome: 'Bem passada', preco: 0 },
        ],
      },
      {
        id: 'grp-002',
        nome: 'Adicionais',
        obrigatorio: false,
        minimo: 0,
        maximo: 5,
        itens: [
          { id: 'ad-004', nome: 'Bacon', preco: 4.0 },
          { id: 'ad-005', nome: 'Ovo', preco: 3.0 },
          { id: 'ad-006', nome: 'Cheddar extra', preco: 3.5 },
          { id: 'ad-007', nome: 'Onion rings', preco: 5.0 },
        ],
      },
    ],
  },
  {
    id: 'prod-002',
    nome: 'X-Salada Especial',
    descricao: 'Pão brioche, hambúrguer 150g, queijo prato, alface crespa, tomate cereja, cebola roxa e maionese verde.',
    fotoUrl: 'https://placehold.co/400x300/FF6961/FFFFFF?text=X-Salada',
    categoria: 'Hambúrgueres',
    preco: 32.5,
    ativo: true,
  },
  {
    id: 'prod-003',
    nome: 'Smash Burger Duplo',
    descricao: 'Dois smash burgers 90g, queijo cheddar derretido, picles e molho smash.',
    fotoUrl: 'https://placehold.co/400x300/FF6961/FFFFFF?text=Smash',
    categoria: 'Hambúrgueres',
    preco: 36.0,
    ativo: true,
  },
  {
    id: 'prod-004',
    nome: 'Pizza Margherita',
    descricao: 'Molho de tomate italiano, mozzarella de búfala, manjericão fresco e azeite extravirgem.',
    fotoUrl: 'https://placehold.co/400x300/FF6961/FFFFFF?text=Margherita',
    categoria: 'Pizzas',
    preco: 49.9,
    ativo: true,
    adicionais: [
      {
        id: 'grp-003',
        nome: 'Tamanho',
        obrigatorio: true,
        minimo: 1,
        maximo: 1,
        itens: [
          { id: 'ad-010', nome: 'Média (6 fatias)', preco: 0 },
          { id: 'ad-011', nome: 'Grande (8 fatias)', preco: 12.0 },
          { id: 'ad-012', nome: 'Família (12 fatias)', preco: 22.0 },
        ],
      },
    ],
  },
  {
    id: 'prod-005',
    nome: 'Pizza Calabresa',
    descricao: 'Molho de tomate, mozzarella, calabresa fatiada e cebola.',
    fotoUrl: 'https://placehold.co/400x300/FF6961/FFFFFF?text=Calabresa',
    categoria: 'Pizzas',
    preco: 44.9,
    ativo: true,
  },
  {
    id: 'prod-006',
    nome: 'Porção de Batata Frita',
    descricao: 'Batata frita crocante temperada com sal e páprica. Serve 2 pessoas.',
    fotoUrl: 'https://placehold.co/400x300/FF6961/FFFFFF?text=Batata',
    categoria: 'Porções',
    preco: 22.0,
    ativo: true,
  },
  {
    id: 'prod-007',
    nome: 'Onion Rings',
    descricao: 'Anéis de cebola empanados e fritos, acompanha molho barbecue.',
    fotoUrl: 'https://placehold.co/400x300/FF6961/FFFFFF?text=Onion+Rings',
    categoria: 'Porções',
    preco: 25.0,
    ativo: true,
  },
  {
    id: 'prod-008',
    nome: 'Coca-Cola 350ml',
    descricao: 'Coca-Cola lata gelada 350ml.',
    fotoUrl: 'https://placehold.co/400x300/FF6961/FFFFFF?text=Coca-Cola',
    categoria: 'Bebidas',
    preco: 7.0,
    ativo: true,
  },
  {
    id: 'prod-009',
    nome: 'Suco de Laranja Natural',
    descricao: 'Suco de laranja natural feito na hora, 500ml.',
    fotoUrl: 'https://placehold.co/400x300/FF6961/FFFFFF?text=Suco',
    categoria: 'Sucos',
    preco: 12.0,
    ativo: true,
  },
  {
    id: 'prod-010',
    nome: 'Milk Shake Chocolate',
    descricao: 'Milk shake cremoso de chocolate com chantilly, 400ml.',
    fotoUrl: 'https://placehold.co/400x300/FF6961/FFFFFF?text=Milkshake',
    categoria: 'Bebidas',
    preco: 18.0,
    ativo: false,
  },
  {
    id: 'prod-011',
    nome: 'Brownie com Sorvete',
    descricao: 'Brownie de chocolate quente com bola de sorvete de baunilha e calda.',
    fotoUrl: 'https://placehold.co/400x300/FF6961/FFFFFF?text=Brownie',
    categoria: 'Sobremesas',
    preco: 19.9,
    ativo: true,
  },
  {
    id: 'prod-012',
    nome: 'Petit Gateau',
    descricao: 'Bolinho de chocolate com centro cremoso, acompanha sorvete de creme.',
    fotoUrl: 'https://placehold.co/400x300/FF6961/FFFFFF?text=Petit+Gateau',
    categoria: 'Sobremesas',
    preco: 24.9,
    ativo: true,
  },
  {
    id: 'prod-013',
    nome: 'Combo Família',
    descricao: '4 X-Burguers + 2 porções de batata frita + 4 refrigerantes.',
    fotoUrl: 'https://placehold.co/400x300/FF6961/FFFFFF?text=Combo',
    categoria: 'Combos',
    preco: 119.9,
    ativo: true,
  },
  {
    id: 'prod-014',
    nome: 'Salada Caesar',
    descricao: 'Alface romana, croutons, parmesão, frango grelhado e molho caesar.',
    fotoUrl: 'https://placehold.co/400x300/FF6961/FFFFFF?text=Caesar',
    categoria: 'Saladas',
    preco: 29.9,
    ativo: true,
  },
  {
    id: 'prod-015',
    nome: 'Prato Executivo Frango',
    descricao: 'Filé de frango grelhado, arroz, feijão, farofa e salada.',
    fotoUrl: 'https://placehold.co/400x300/FF6961/FFFFFF?text=Executivo',
    categoria: 'Pratos Executivos',
    preco: 26.9,
    ativo: true,
  },
];
